### ISSUE TITLE
rxbreakout pox.xml dependency issue

### ISSUE THREAD

**Issue by rob5n** [ibaca/rxcanvas-gwt#1]
I tried to build rxbreakout and got the following error:

[ERROR] Failed to execute goal on project rxbreakout-gwt: Could not resolve dependencies for project com.intendia:rxbreakout-gwt:gwt-app:1.0
-SNAPSHOT: Could not find artifact com.intendia.gwt.rxgwt2:rxgwt:jar:HEAD-SNAPSHOT

I then built rxcanvas fine.  It must have downloaded the missing dependency to local maven repo, because then I was able to build rxbreakout successfully.

**Comment by ibaca** [comment]
Oh, yep it has missing sonatype snapshot repositories. Fixed, thanks!
